package com.winit.alseer.salesman.common;
/**
 * this class will have some constant values to make differentiate the different different conditions
 */
public enum CONSTANTOBJ
{
//	PRINT_VERIFY_ITEMS_IN_VEHICLE,
//	PRINT_VERIFY_STOCK_UNLOAD,
	PRINT_SALES,
	PRINT_SALES_PREVIEW,
	PAYMENT_RECEIPT,
	PRINT_LOG_REPORT,
//	NEW_CUSTOMER,
//	ORDER_SUMMARY,
	PAYMENT_SUMMARY,
//	TRANSFER_IN,
//	TRANSFER_OUT,
//	PRINT_FREEDELIVERY,
//	PRINT_RETURN_INVENTORY,
	PRINT_INVENTORY,
	PRINT_VERIFY_INVENTOTY,
	PRINT_PENDING_INVOICE,
	PRINT_CUSTOMER_STATEMENT,
//	PRINT_CUSTOMER_PAYMENT_SUMMARY,
//	PRINT_ORDER_SUMMARY,
	PRINT_SAMPLE,
	PRINT_CASH_DENOMINATION,
	PRINT_DAILY_SUMMARY,
	PRINT_STOCK_INVENTORY,
	PRINT_STOCK_DETAILS
}
